on: [workflow_call]

jobs:

  name: Check-Dockerfile
  check:
    runs-on: ubuntu-latest
    outputs:
      docker: ${{ steps.filter.outputs.docker }}
    steps:
      - uses: actions/checkout@v4

      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            docker:
              - './.github/workflows/Dockerfile'

  Build-Image:
    needs: check
    if: ${{ needs.check.outputs.docker == true }}
    runs-on: ubuntu-latest

    steps:

      - run: echo "Docker-Built"

  Build-Code:
    needs: Build-Image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: |
          touch ascot5_main
          touch libascot
          ls -l ascot5_main
          chmod +x ascot5_main
          ls -l ascot5_main
          tar -cf archive.tar ascot5_main libascot

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: ascot5_main
          path: |
            archive.tar
