name: Compile
on: [workflow_call]

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: |
          touch ascot5_main
          touch libascot
          ls -l ascot5_main
          chmod +x ascot5_main
          ls -l ascot5_main

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: ascot5_main
          path: |
            ascot5_main
            libascot
