name: Run
on: [push, workflow_dispatch]

jobs:
  job1:
    uses: miekkasarki/workflows/.github/workflows/compile.yaml@main

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Download
        uses: actions/download-artifact@main
        with:
          name: ascot5_main

      - run: |
         ls -l ascot5_main
         ls -l libascot
